name: "upzy-ingestor"

services:
  ingestor:
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: ./services/ingestor/Dockerfile
    environment:
      - POSTGRES_URL=postgres://upzy:upzypass@timescaledb:5432/upzy_database
      - REDIS_URL=redis://redis-stack:6379
      - INGESTOR_WORKER_COUNT=10
      - INGESTOR_BATCH_SIZE=500
      - INGESTOR_BATCH_TIMEOUT_SEC=5
    networks:
    - upzy_net

networks:
  upzy_net:
    external: true