// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMonitorJob = `-- name: GetMonitorJob :one
SELECT 
  id, 
  url, 
  type, 
  http_method, 
  request_timeout, 
  request_body, 
  request_headers, 
  expected_status_codes, 
  expected_response_time, 
  verify_ssl, 
  follow_redirects,
  -- TraceID is generated at runtime
  ''::text as trace_id
FROM monitors
WHERE id = $1
`

type GetMonitorJobRow struct {
	ID                   string         `json:"id"`
	Url                  string         `json:"url"`
	Type                 MonitorType    `json:"type"`
	HttpMethod           NullHttpMethod `json:"http_method"`
	RequestTimeout       int32          `json:"request_timeout"`
	RequestBody          pgtype.Text    `json:"request_body"`
	RequestHeaders       []byte         `json:"request_headers"`
	ExpectedStatusCodes  []int32        `json:"expected_status_codes"`
	ExpectedResponseTime pgtype.Int4    `json:"expected_response_time"`
	VerifySsl            bool           `json:"verify_ssl"`
	FollowRedirects      bool           `json:"follow_redirects"`
	TraceID              string         `json:"trace_id"`
}

func (q *Queries) GetMonitorJob(ctx context.Context, id string) (GetMonitorJobRow, error) {
	row := q.db.QueryRow(ctx, getMonitorJob, id)
	var i GetMonitorJobRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Type,
		&i.HttpMethod,
		&i.RequestTimeout,
		&i.RequestBody,
		&i.RequestHeaders,
		&i.ExpectedStatusCodes,
		&i.ExpectedResponseTime,
		&i.VerifySsl,
		&i.FollowRedirects,
		&i.TraceID,
	)
	return i, err
}
