// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package db

import (
	"context"
)

const listActiveMonitors = `-- name: ListActiveMonitors :many
SELECT id, created_by_id, organization_id, name, slug, url, type, interval, request_timeout, retry_count, enabled, is_paused, http_method, request_body, request_headers, expected_status_codes, expected_response_time, follow_redirects, verify_ssl, ssl_check_enabled, ssl_expiry_threshold, auth_type, auth_username, auth_password, auth_token, dns_server, dns_record_type, expected_ip, playwright_script, heartbeat_grace_period, regions, tags, last_check_at, created_at, updated_at FROM monitors
WHERE enabled = true AND is_paused = false
`

func (q *Queries) ListActiveMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listActiveMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Url,
			&i.Type,
			&i.Interval,
			&i.RequestTimeout,
			&i.RetryCount,
			&i.Enabled,
			&i.IsPaused,
			&i.HttpMethod,
			&i.RequestBody,
			&i.RequestHeaders,
			&i.ExpectedStatusCodes,
			&i.ExpectedResponseTime,
			&i.FollowRedirects,
			&i.VerifySsl,
			&i.SslCheckEnabled,
			&i.SslExpiryThreshold,
			&i.AuthType,
			&i.AuthUsername,
			&i.AuthPassword,
			&i.AuthToken,
			&i.DnsServer,
			&i.DnsRecordType,
			&i.ExpectedIp,
			&i.PlaywrightScript,
			&i.HeartbeatGracePeriod,
			&i.Regions,
			&i.Tags,
			&i.LastCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
