services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      # Set your desired database name, user, and password here
      POSTGRES_DB: upzy_database
      POSTGRES_USER: upzy
      POSTGRES_PASSWORD: upzypass
    volumes:
      # Persist PostgreSQL data to a named volume
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_web
    ports:
      - "5050:80"
    environment:
      # Set your desired pgAdmin login email and password here
      PGADMIN_DEFAULT_EMAIL: admin@upzy.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    volumes:
      # Persist pgAdmin configuration to a named volume
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      # Ensure PostgreSQL starts before pgAdmin
      - postgres

volumes:
  # Define named volumes for data persistence
  postgres_data:
  pgadmin_data:
